version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  influxdb:
    image: influxdb:2.7.10
    ports:
      - "8089:8089"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: omayma
      DOCKER_INFLUXDB_INIT_PASSWORD: Centralparc
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: kafka-consumer
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "4dzbMMlP8gKguTWo1cko0SoW222FHQ1A27lNnk09pQ1t3Xmi8OeAXg6ekqgKsNl-6tf-fOJQwCBcSv-KSHIvmA=="
